### ISSUE TITLE
Pandas 1.3.0 (but not 1.3.1) support on purpose?

### ISSUE THREAD

**Issue by Anthchirp** [Hekstra-Lab/reciprocalspaceship#77] opened 2021-08-18 13:04 UTC
f803979bd565eaeedbdb7c514701b57b25cf750d added explicit support for version 1.3.0, but excluded patch releases such as 1.3.1.

Was that on purpose or should the expression read `<1.4`?

**Comment by kmdalton** [comment] 2021-08-18 13:43
This is @JBGreisman 's department, but I recall that Pandas has been mucking around with custom `dtypes` lately and breaking everything. I would not be surprised if the very specific versioning requirement was just self defense.

**Comment by JBGreisman** [comment] 2021-08-18 18:42
This was mostly done in self defense as @kmdalton suggested. There are two places that `rs` has historically run into issues during pandas updates:

The first is with attributes for our subclassed `DataFrame` (`rs.DataSet`). In the olde days of this project, there were a few pandas operations that would lead to loss of the subclass , and therefore loss of `cell` and `spacegroup` attributes. That has largely stabilized in the last couple of years and hasn't caused trouble lately. 

The second place is with our `ExtensionDtypes` that are used to implement all the MTZ datatypes. Pandas adjusts that API a bit more regularly, and also sometimes changes behavior in small ways during patch releases. I had set a maximal version to protect against short-term issues, but I think that was the wrong approach to this problem. 

I think it makes the most sense to have a GitHub Action that tests the build on a set schedule to detect possible issues with any latest pandas version. This sort of "detect early" strategy is a bit more flexible, and should allow us to keep up to date with pandas in a more seamless manner.

**Comment by JBGreisman** [comment] 2021-08-18 19:19
To do list:
- [ ] Extend supported version to latest pandas (1.3.2)
- [ ] Add schedule to GitHub action to try building `rs` on a regular (daily?) basis. Failed builds will email team/followers.
- [ ] Remove maximal pandas version. Minimal version will be kept because pandas 1.2.0 was when `FloatingDtype` was introduced, which backs our floating-point MTZDtypes

**Comment by Anthchirp** [comment] 2021-08-23 18:28
We use renovate to track and test against dependency updates, eg. DiamondLightSource/python-workflows#65

**Comment by JBGreisman** [comment] 2021-08-23 18:45
awesome -- good to hear. I had been looking into that as a possible solution for this

**Comment by JBGreisman** [comment] 2021-08-23 19:33
I tested `renovate` in my personal fork and it seems accomplish this task exactly as I hoped. I tested it by reverting the pandas version to "pandas >= 1.2.0, <= 1.3.0", and `renovate` filed a PR to change the line to read "pandas >= 1.2.0, <= 1.3.2".

**Comment by JBGreisman** [comment] 2021-08-23 20:21
I'm closing this issue because `renovate` has now been added to the repo, and appears to be working as intended

**Closed by JBGreisman** 2021-08-23 20:21 UTC
Labels: question, MTZDtypes, version
