### ISSUE TITLE
pandas version issue?

### ISSUE THREAD

**Issue by DHekstra** [Hekstra-Lab/reciprocalspaceship#155] opened 2022-05-27 18:13 UTC
Starting a clean conda env in a test run for a workshop at the Erice summer school. 
When I `conda install -c conda-forge reciprocalspaceship`, it installs pandas-1.4.2, but on import, it throws an error: `The 'pandas<=1.3.0,>=1.2.0' distribution was not found and is required by reciprocalspaceship.`

**Comment by dennisbrookner** [comment] 2022-05-27 19:42
I also got this error message at one point, though it eventually went away and I'm not sure I could reproduce it.

**Comment by kmdalton** [comment] 2022-05-27 19:57
I can confirm this issue with the `conda-forge` package. For now, you can use `pip` to install.

**Comment by JBGreisman** [comment] 2022-05-27 22:27
yeah -- this is because the conda-forge recipe is out of date: https://github.com/conda-forge/reciprocalspaceship-feedstock/blob/e8c22b4f4f04210dc48f1046acb9d58419814c4c/recipe/meta.yaml#L28

I'll push a new release to PyPI, and will make a new conda-forge release to update this.

**Comment by JBGreisman** [comment] 2022-05-28 01:16
This should be fixed now with `rs 0.10.1`. I made a clean environment, and it seems to work correctly for me. I'm going to close this issue, but feel free to re-open it if you still run into issues with this.

**Closed by JBGreisman** 2022-05-28 01:16 UTC
Labels: bug, version
